channels:
  - conda-forge
  - defaults
dependencies:
  - dask
  - numba
  - pip
  - nodejs
  - graphviz
  - itkwidgets>=0.32.0
  - numpy
  - itk>=5.1.1
  - scikit-image
  - dask[complete]
  - dask-image
  - dask-labextension
  - ipykernel
  - graphviz
  - distributed
  - pandas
  - jupyterlab
  - scipy
  - requests
  - toolz
  - zarr
  - xarray
  - fsspec>=0.8.4
  - ipympl
  - plotly
  - ipywidgets>=7.5.1
  - coiled
  - cftime
  - skan
  - pip
  - pip:
    - itk-thickness3d
